/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<number, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccesoFactoresMfa {
  creado_en: Generated<Timestamp>;
  id: Generated<string>;
  secreto_cifrado: Buffer;
  tipo: string;
  usuario_id: string;
}

export interface AccesoPermisos {
  codigo: string;
  descripcion: string;
}

export interface AccesoRoles {
  codigo: string;
  descripcion: string | null;
  nombre: string;
}

export interface AccesoRolPermisos {
  permiso_codigo: string;
  rol_codigo: string;
}

export interface AccesoSesiones {
  cerrada_en: Timestamp | null;
  id: Generated<string>;
  iniciada_en: Generated<Timestamp>;
  ip: string | null;
  user_agent: string | null;
  usuario_id: string;
}

export interface AccesoUsuarioRoles {
  rol_codigo: string;
  usuario_id: string;
}

export interface AccesoUsuarios {
  activo: Generated<boolean>;
  creado_en: Generated<Timestamp>;
  id: Generated<string>;
  login: string;
  password_hash: string;
  persona_id: string;
}

export interface AccesoUsuarioTerritorios {
  territorio_id: number;
  usuario_id: string;
}

export interface AccesoVPermisosUsuarios {
  login: string | null;
  permiso_codigo: string | null;
  rol_codigo: string | null;
  usuario_id: string | null;
}

export interface AuditoriaEventoCampos {
  campo: string;
  evento_id: number;
}

export interface AuditoriaEventos {
  accion: string;
  esquema: string | null;
  id: Generated<number>;
  ip: string | null;
  ocurrido_en: Generated<Timestamp>;
  registro_id: string | null;
  tabla: string | null;
  usuario_id: string | null;
}

export interface AuditoriaExportaciones {
  cantidad_registros: number;
  exportado_en: Generated<Timestamp>;
  formato: string;
  id: Generated<number>;
  motivo: string;
  usuario_id: string;
}

export interface AuditoriaExportacionTerritorios {
  exportacion_id: number;
  territorio_id: number;
}

export interface AuditoriaVActividadUsuarios {
  accion: string | null;
  eventos: number | null;
  fecha: Timestamp | null;
  login: string | null;
  usuario_id: string | null;
}

export interface CalidadAlertaMiembros {
  alerta_id: string;
  miembro_id: string;
}

export interface CalidadAlertaPersonas {
  alerta_id: string;
  persona_id: string;
}

export interface CalidadAlertas {
  detectada_en: Generated<Timestamp>;
  estado: Generated<string>;
  id: Generated<string>;
  observacion: string | null;
  resuelta_en: Timestamp | null;
  resuelta_por: string | null;
  tipo_codigo: string;
}

export interface CalidadIntentosDuplicado {
  canal_codigo: string;
  id: Generated<number>;
  intentado_en: Generated<Timestamp>;
  link_referido_id: string;
  persona_existente_id: string;
}

export interface CalidadTiposAlerta {
  codigo: string;
  descripcion: string;
  severidad: string;
}

export interface CalidadVAlertasAbiertas {
  detectada_en: Timestamp | null;
  estado: string | null;
  id: string | null;
  miembros: number | null;
  observacion: string | null;
  personas: number | null;
  severidad: string | null;
  tipo_codigo: string | null;
}

export interface CampanaCanalesRegistro {
  codigo: string;
  nombre: string;
}

export interface CampanaCargos {
  codigo: string;
  nivel: number;
  nombre: string;
}

export interface CampanaEstadosSimpatizante {
  codigo: string;
  nombre: string;
}

export interface CampanaLinksReferido {
  activo: Generated<boolean>;
  codigo: string;
  creado_en: Generated<Timestamp>;
  es_principal: Generated<boolean>;
  expira_en: Timestamp | null;
  id: Generated<string>;
  miembro_id: string;
}

export interface CampanaMetasMiembro {
  cantidad: number;
  fecha_inicio: Timestamp;
  fecha_limite: Timestamp;
  id: Generated<number>;
  miembro_id: string;
}

export interface CampanaMetasTerritorio {
  cantidad: number;
  fecha_inicio: Timestamp;
  fecha_limite: Timestamp;
  id: Generated<number>;
  territorio_id: number;
}

export interface CampanaMiembros {
  activo: Generated<boolean>;
  cargo_codigo: string;
  fecha_ingreso: Generated<Timestamp>;
  id: Generated<string>;
  persona_id: string;
  superior_id: string | null;
}

export interface CampanaMiembroTerritorios {
  miembro_id: string;
  territorio_id: number;
}

export interface CampanaMvConteoTerritorio {
  simpatizantes: number | null;
  territorio_id: number | null;
}

export interface CampanaParametros {
  clave: string;
  descripcion: string;
  valor: string;
}

export interface CampanaSimpatizantePuesto {
  fuente: Generated<string>;
  jornada_id: number;
  persona_id: string;
  puesto_id: number;
  registrado_en: Generated<Timestamp>;
}

export interface CampanaSimpatizantes {
  canal_codigo: string;
  capturado_en: Timestamp;
  estado_codigo: Generated<string>;
  link_referido_id: string;
  persona_id: string;
  recibido_en: Generated<Timestamp>;
  registrado_por: string | null;
  territorio_residencia_id: number;
  ubicacion: string | null;
}

export interface CampanaVAvanceMetasMiembro {
  fecha_inicio: Timestamp | null;
  fecha_limite: Timestamp | null;
  meta: number | null;
  miembro_id: string | null;
  porcentaje: Numeric | null;
  registrados: number | null;
}

export interface CampanaVAvanceMetasTerritorio {
  fecha_limite: Timestamp | null;
  meta: number | null;
  porcentaje: Numeric | null;
  registrados: number | null;
  territorio: string | null;
  territorio_id: number | null;
}

export interface CampanaVLideresInactivos {
  activos: number | null;
  cargo_codigo: string | null;
  intentos_duplicado: number | null;
  miembro_id: string | null;
  nombre: string | null;
  ultimo_registro: Timestamp | null;
  ultimos_7_dias: number | null;
}

export interface CampanaVRankingMiembros {
  activos: number | null;
  cargo_codigo: string | null;
  intentos_duplicado: number | null;
  miembro_id: string | null;
  nombre: string | null;
  ultimo_registro: Timestamp | null;
  ultimos_7_dias: number | null;
}

export interface CampanaVRedMiembros {
  activo: boolean | null;
  camino: string[] | null;
  cargo_codigo: string | null;
  miembro_id: string | null;
  nombre: string | null;
  profundidad: number | null;
  superior_id: string | null;
}

export interface CampanaVRegistrosDiarios {
  canal_codigo: string | null;
  fecha: Timestamp | null;
  municipio_id: number | null;
  registros: number | null;
}

export interface CampanaVSimpatizantes {
  apellidos: string | null;
  canal_codigo: string | null;
  capturado_en: Timestamp | null;
  estado_codigo: string | null;
  municipio: string | null;
  municipio_id: number | null;
  nombres: string | null;
  persona_id: string | null;
  referido_por: string | null;
  referido_por_miembro_id: string | null;
  territorio_residencia: string | null;
  territorio_residencia_id: number | null;
}

export interface CampanaVTablero {
  alertas_abiertas: number | null;
  miembros_activos: number | null;
  necesidades_reportadas: number | null;
  registros_hoy: number | null;
  registros_semana: number | null;
  simpatizantes_activos: number | null;
}

export interface ChatbotConversaciones {
  canal_codigo: string;
  finalizada_en: Timestamp | null;
  id: Generated<string>;
  identificador_externo_hash: Buffer | null;
  iniciada_en: Generated<Timestamp>;
  link_referido_id: string | null;
  persona_id: string | null;
  resultado: string | null;
}

export interface ChatbotMensajes {
  contenido: string;
  conversacion_id: string;
  emisor: string;
  enviado_en: Generated<Timestamp>;
  id: Generated<number>;
}

export interface ComunicacionesBajas {
  canal_codigo: string;
  persona_id: string;
  solicitada_en: Generated<Timestamp>;
}

export interface ComunicacionesCanales {
  codigo: string;
  nombre: string;
}

export interface ComunicacionesEnvioDestinatarios {
  envio_id: string;
  error: string | null;
  estado: Generated<string>;
  persona_id: string;
  procesado_en: Timestamp | null;
}

export interface ComunicacionesEnvios {
  creado_por: string;
  estado: Generated<string>;
  id: Generated<string>;
  plantilla_id: string;
  programado_para: Timestamp;
}

export interface ComunicacionesEnvioTerritorios {
  envio_id: string;
  territorio_id: number;
}

export interface ComunicacionesNotificaciones {
  creada_en: Generated<Timestamp>;
  cuerpo: string;
  id: Generated<string>;
  leida_en: Timestamp | null;
  titulo: string;
  usuario_id: string;
}

export interface ComunicacionesPlantillas {
  aprobada_en: Timestamp | null;
  aprobada_por: string | null;
  canal_codigo: string;
  contenido: string;
  id: Generated<string>;
  nombre: string;
}

export interface ComunicacionesVContactables {
  canal_codigo: string | null;
  persona_id: string | null;
}

export interface ComunicacionesVResumenEnvios {
  canal_codigo: string | null;
  destinatarios: number | null;
  enviados: number | null;
  estado: string | null;
  fallidos: number | null;
  id: string | null;
  omitidos: number | null;
  plantilla: string | null;
  programado_para: Timestamp | null;
}

export interface CumplimientoAutorizaciones {
  canal_codigo: string;
  evidencia: string;
  id: Generated<string>;
  ip: string | null;
  otorgada_en: Generated<Timestamp>;
  persona_id: string;
  politica_version: number;
  revocada_en: Timestamp | null;
  user_agent: string | null;
}

export interface CumplimientoAutorizacionFinalidades {
  autorizacion_id: string;
  finalidad_codigo: string;
}

export interface CumplimientoFinalidades {
  codigo: string;
  descripcion: string;
}

export interface CumplimientoPoliticaFinalidades {
  finalidad_codigo: string;
  politica_version: number;
}

export interface CumplimientoPoliticasTratamiento {
  hash_texto: Buffer;
  texto: string;
  version: number;
  vigente_desde: Timestamp;
  vigente_hasta: Timestamp | null;
}

export interface CumplimientoSolicitudesTitular {
  contacto_respuesta: string;
  descripcion: string;
  estado: Generated<string>;
  id: Generated<string>;
  persona_id: string | null;
  radicado: string;
  recibida_en: Generated<Timestamp>;
  respondida_en: Timestamp | null;
  respuesta: string | null;
  tipo_codigo: string;
}

export interface CumplimientoTiposSolicitud {
  codigo: string;
  nombre: string;
  plazo_dias_habiles: number;
}

export interface CumplimientoVControlAutorizaciones {
  capturado_en: Timestamp | null;
  estado_codigo: string | null;
  persona_id: string | null;
}

export interface CumplimientoVSolicitudesPlazos {
  estado: string | null;
  fecha_limite: Timestamp | null;
  id: string | null;
  radicado: string | null;
  recibida_en: Timestamp | null;
  semaforo: string | null;
  tipo_codigo: string | null;
}

export interface ElectoralCorporaciones {
  codigo: string;
  nombre: string;
}

export interface ElectoralFormulariosE14 {
  archivo_ruta: string;
  archivo_sha256: Buffer;
  cargado_en: Generated<Timestamp>;
  cargado_por: string;
  corporacion_codigo: string;
  estado_revision: Generated<string>;
  id: Generated<string>;
  mesa_id: number;
}

export interface ElectoralJornadas {
  fecha: Timestamp;
  id: Generated<number>;
  nombre: string;
  tipo_codigo: string;
}

export interface ElectoralMesas {
  id: Generated<number>;
  jornada_id: number;
  numero: number;
  puesto_id: number;
}

export interface ElectoralOpcionesVoto {
  corporacion_codigo: string;
  es_candidato_propio: Generated<boolean>;
  id: Generated<number>;
  jornada_id: number;
  nombre: string;
  partido_id: number | null;
  tipo: string;
}

export interface ElectoralPartidos {
  id: Generated<number>;
  nombre: string;
}

export interface ElectoralPuestosJornada {
  jornada_id: number;
  potencial_electoral: number | null;
  puesto_id: number;
}

export interface ElectoralPuestosJornadaCorporaciones {
  corporacion_codigo: string;
  jornada_id: number;
  puesto_id: number;
}

export interface ElectoralPuestosVotacion {
  codigo_registraduria: string | null;
  direccion: string | null;
  geom: string | null;
  id: Generated<number>;
  nombre: string;
  territorio_id: number;
}

export interface ElectoralResultadosE14 {
  formulario_id: string;
  opcion_voto_id: number;
  votos: number;
}

export interface ElectoralTestigos {
  asignado_en: Generated<Timestamp>;
  estado: Generated<string>;
  mesa_id: number;
  miembro_id: string;
}

export interface ElectoralTiposJornada {
  codigo: string;
  nombre: string;
}

export interface ElectoralVBrechaPuestos {
  cobertura_pct: Numeric | null;
  geom: string | null;
  jornada_id: number | null;
  municipio_id: number | null;
  potencial_electoral: number | null;
  puesto: string | null;
  puesto_id: number | null;
  simpatizantes: number | null;
}

export interface ElectoralVCoberturaTestigos {
  jornada_id: number | null;
  mesas: number | null;
  mesas_con_testigo: number | null;
  mesas_sin_testigo: number | null;
  puesto: string | null;
  puesto_id: number | null;
}

export interface ElectoralVConteoRapido {
  corporacion_codigo: string | null;
  es_candidato_propio: boolean | null;
  jornada_id: number | null;
  mesas_reportadas: number | null;
  opcion: string | null;
  votos: number | null;
}

export interface ElectoralVOrigenVotantesPuesto {
  jornada_id: number | null;
  puesto_id: number | null;
  simpatizantes: number | null;
  territorio_residencia_id: number | null;
}

export interface EventosAsistencias {
  evento_id: string;
  metodo: string;
  persona_id: string;
  registrada_en: Generated<Timestamp>;
}

export interface EventosEventos {
  codigo_checkin: string;
  creado_por: string;
  descripcion: string | null;
  id: Generated<string>;
  inicia_en: Timestamp;
  lugar: string | null;
  nombre: string;
  termina_en: Timestamp;
  territorio_id: number;
  tipo_codigo: string;
}

export interface EventosOrganizadores {
  evento_id: string;
  miembro_id: string;
}

export interface EventosTiposEvento {
  codigo: string;
  nombre: string;
}

export interface EventosVResumenEventos {
  asistentes: number | null;
  asistentes_simpatizantes: number | null;
  id: string | null;
  inicia_en: Timestamp | null;
  nombre: string | null;
  registrados_en_evento: number | null;
  territorio: string | null;
  tipo_codigo: string | null;
}

export interface ParticipacionCategoriasNecesidad {
  codigo: string;
  nombre: string;
}

export interface ParticipacionClasificacionesIa {
  categoria_codigo: string;
  clasificada_en: Generated<Timestamp>;
  confianza: Numeric;
  modelo: string;
  necesidad_id: string;
}

export interface ParticipacionEjesPrograma {
  codigo: string;
  nombre: string;
  orden: number;
}

export interface ParticipacionNecesidades {
  categoria_codigo: string | null;
  descripcion: string;
  id: Generated<string>;
  persona_id: string | null;
  reportada_en: Generated<Timestamp>;
  territorio_id: number;
}

export interface ParticipacionPropuestaCategorias {
  categoria_codigo: string;
  propuesta_id: string;
}

export interface ParticipacionPropuestas {
  actualizada_en: Generated<Timestamp>;
  contenido: string;
  eje_codigo: string;
  id: Generated<string>;
  publicada: Generated<boolean>;
  titulo: string;
}

export interface ParticipacionPropuestaTerritorios {
  propuesta_id: string;
  territorio_id: number;
}

export interface ParticipacionVNecesidadesMunicipio {
  cantidad: number | null;
  categoria_codigo: string | null;
  municipio_id: number | null;
}

export interface ParticipacionVNecesidadesSinPropuesta {
  codigo: string | null;
  necesidades: Numeric | null;
  nombre: string | null;
}

export interface PersonasCorreos {
  correo: string;
  es_principal: Generated<boolean>;
  persona_id: string;
  verificado: Generated<boolean>;
}

export interface PersonasPersonas {
  apellidos: string;
  creado_en: Generated<Timestamp>;
  documento_cifrado: Buffer;
  documento_hash: Buffer;
  id: Generated<string>;
  nombres: string;
  tipo_documento_codigo: string;
}

export interface PersonasTelefonos {
  es_principal: Generated<boolean>;
  id: Generated<string>;
  persona_id: string;
  telefono_cifrado: Buffer;
  telefono_hash: Buffer;
}

export interface PersonasTiposDocumento {
  codigo: string;
  nombre: string;
}

export interface TerritorioFuentesGeograficas {
  entidad: string;
  fecha_obtencion: Timestamp | null;
  id: Generated<number>;
  nombre: string;
  url: string | null;
  version: string | null;
}

export interface TerritorioNombresAlternos {
  nombre: string;
  territorio_id: number;
}

export interface TerritorioTerritorios {
  codigo_oficial: string | null;
  creado_en: Generated<Timestamp>;
  fuente_id: number;
  geom: string | null;
  id: Generated<number>;
  nombre: string;
  padre_id: number | null;
  tipo_codigo: string;
  verificado: Generated<boolean>;
}

export interface TerritorioTiposTerritorio {
  codigo: string;
  nivel: number;
  nombre: string;
}

export interface TerritorioVJerarquia {
  codigo_oficial: string | null;
  departamento_id: number | null;
  id: number | null;
  municipio_id: number | null;
  nivel: number | null;
  nombre: string | null;
  padre_id: number | null;
  ruta: string | null;
  tiene_poligono: boolean | null;
  tipo_codigo: string | null;
  verificado: boolean | null;
}

export interface TerritorioVMapa {
  geom: string | null;
  id: number | null;
  nombre: string | null;
  padre_id: number | null;
  simpatizantes: number | null;
  subdivisiones: number | null;
  tipo_codigo: string | null;
}

export interface TerritorioVZonasSinCobertura {
  geom: string | null;
  id: number | null;
  municipio: string | null;
  nombre: string | null;
  tipo_codigo: string | null;
}

export interface DB {
  "acceso.factores_mfa": AccesoFactoresMfa;
  "acceso.permisos": AccesoPermisos;
  "acceso.rol_permisos": AccesoRolPermisos;
  "acceso.roles": AccesoRoles;
  "acceso.sesiones": AccesoSesiones;
  "acceso.usuario_roles": AccesoUsuarioRoles;
  "acceso.usuario_territorios": AccesoUsuarioTerritorios;
  "acceso.usuarios": AccesoUsuarios;
  "acceso.v_permisos_usuarios": AccesoVPermisosUsuarios;
  "auditoria.evento_campos": AuditoriaEventoCampos;
  "auditoria.eventos": AuditoriaEventos;
  "auditoria.exportacion_territorios": AuditoriaExportacionTerritorios;
  "auditoria.exportaciones": AuditoriaExportaciones;
  "auditoria.v_actividad_usuarios": AuditoriaVActividadUsuarios;
  "calidad.alerta_miembros": CalidadAlertaMiembros;
  "calidad.alerta_personas": CalidadAlertaPersonas;
  "calidad.alertas": CalidadAlertas;
  "calidad.intentos_duplicado": CalidadIntentosDuplicado;
  "calidad.tipos_alerta": CalidadTiposAlerta;
  "calidad.v_alertas_abiertas": CalidadVAlertasAbiertas;
  "campana.canales_registro": CampanaCanalesRegistro;
  "campana.cargos": CampanaCargos;
  "campana.estados_simpatizante": CampanaEstadosSimpatizante;
  "campana.links_referido": CampanaLinksReferido;
  "campana.metas_miembro": CampanaMetasMiembro;
  "campana.metas_territorio": CampanaMetasTerritorio;
  "campana.miembro_territorios": CampanaMiembroTerritorios;
  "campana.miembros": CampanaMiembros;
  "campana.mv_conteo_territorio": CampanaMvConteoTerritorio;
  "campana.parametros": CampanaParametros;
  "campana.simpatizante_puesto": CampanaSimpatizantePuesto;
  "campana.simpatizantes": CampanaSimpatizantes;
  "campana.v_avance_metas_miembro": CampanaVAvanceMetasMiembro;
  "campana.v_avance_metas_territorio": CampanaVAvanceMetasTerritorio;
  "campana.v_lideres_inactivos": CampanaVLideresInactivos;
  "campana.v_ranking_miembros": CampanaVRankingMiembros;
  "campana.v_red_miembros": CampanaVRedMiembros;
  "campana.v_registros_diarios": CampanaVRegistrosDiarios;
  "campana.v_simpatizantes": CampanaVSimpatizantes;
  "campana.v_tablero": CampanaVTablero;
  "chatbot.conversaciones": ChatbotConversaciones;
  "chatbot.mensajes": ChatbotMensajes;
  "comunicaciones.bajas": ComunicacionesBajas;
  "comunicaciones.canales": ComunicacionesCanales;
  "comunicaciones.envio_destinatarios": ComunicacionesEnvioDestinatarios;
  "comunicaciones.envio_territorios": ComunicacionesEnvioTerritorios;
  "comunicaciones.envios": ComunicacionesEnvios;
  "comunicaciones.notificaciones": ComunicacionesNotificaciones;
  "comunicaciones.plantillas": ComunicacionesPlantillas;
  "comunicaciones.v_contactables": ComunicacionesVContactables;
  "comunicaciones.v_resumen_envios": ComunicacionesVResumenEnvios;
  "cumplimiento.autorizacion_finalidades": CumplimientoAutorizacionFinalidades;
  "cumplimiento.autorizaciones": CumplimientoAutorizaciones;
  "cumplimiento.finalidades": CumplimientoFinalidades;
  "cumplimiento.politica_finalidades": CumplimientoPoliticaFinalidades;
  "cumplimiento.politicas_tratamiento": CumplimientoPoliticasTratamiento;
  "cumplimiento.solicitudes_titular": CumplimientoSolicitudesTitular;
  "cumplimiento.tipos_solicitud": CumplimientoTiposSolicitud;
  "cumplimiento.v_control_autorizaciones": CumplimientoVControlAutorizaciones;
  "cumplimiento.v_solicitudes_plazos": CumplimientoVSolicitudesPlazos;
  "electoral.corporaciones": ElectoralCorporaciones;
  "electoral.formularios_e14": ElectoralFormulariosE14;
  "electoral.jornadas": ElectoralJornadas;
  "electoral.mesas": ElectoralMesas;
  "electoral.opciones_voto": ElectoralOpcionesVoto;
  "electoral.partidos": ElectoralPartidos;
  "electoral.puestos_jornada": ElectoralPuestosJornada;
  "electoral.puestos_jornada_corporaciones": ElectoralPuestosJornadaCorporaciones;
  "electoral.puestos_votacion": ElectoralPuestosVotacion;
  "electoral.resultados_e14": ElectoralResultadosE14;
  "electoral.testigos": ElectoralTestigos;
  "electoral.tipos_jornada": ElectoralTiposJornada;
  "electoral.v_brecha_puestos": ElectoralVBrechaPuestos;
  "electoral.v_cobertura_testigos": ElectoralVCoberturaTestigos;
  "electoral.v_conteo_rapido": ElectoralVConteoRapido;
  "electoral.v_origen_votantes_puesto": ElectoralVOrigenVotantesPuesto;
  "eventos.asistencias": EventosAsistencias;
  "eventos.eventos": EventosEventos;
  "eventos.organizadores": EventosOrganizadores;
  "eventos.tipos_evento": EventosTiposEvento;
  "eventos.v_resumen_eventos": EventosVResumenEventos;
  "participacion.categorias_necesidad": ParticipacionCategoriasNecesidad;
  "participacion.clasificaciones_ia": ParticipacionClasificacionesIa;
  "participacion.ejes_programa": ParticipacionEjesPrograma;
  "participacion.necesidades": ParticipacionNecesidades;
  "participacion.propuesta_categorias": ParticipacionPropuestaCategorias;
  "participacion.propuesta_territorios": ParticipacionPropuestaTerritorios;
  "participacion.propuestas": ParticipacionPropuestas;
  "participacion.v_necesidades_municipio": ParticipacionVNecesidadesMunicipio;
  "participacion.v_necesidades_sin_propuesta": ParticipacionVNecesidadesSinPropuesta;
  "personas.correos": PersonasCorreos;
  "personas.personas": PersonasPersonas;
  "personas.telefonos": PersonasTelefonos;
  "personas.tipos_documento": PersonasTiposDocumento;
  "territorio.fuentes_geograficas": TerritorioFuentesGeograficas;
  "territorio.nombres_alternos": TerritorioNombresAlternos;
  "territorio.territorios": TerritorioTerritorios;
  "territorio.tipos_territorio": TerritorioTiposTerritorio;
  "territorio.v_jerarquia": TerritorioVJerarquia;
  "territorio.v_mapa": TerritorioVMapa;
  "territorio.v_zonas_sin_cobertura": TerritorioVZonasSinCobertura;
}
