import { useEffect, useState, type FormEvent } from 'react';
import { useQuery, useQueryClient, type UseQueryResult } from '@tanstack/react-query';
import { CircleMarker, GeoJSON, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet';
import * as L from 'leaflet';
import { api, type AgendaCatalogos, type AgendaCompromiso, type AgendaDetalle, type AgendaVisita } from '../api/cliente';
import { Cargando, ErrorEstado } from '../componentes/Estados';
import { useSesion } from '../sesion/SesionContext';
import { NuevaVisitaForm } from './NuevaVisitaForm';
import { AsistenciaEvento } from './AsistenciaEvento';
import { ComparativoAsistencia } from './ComparativoAsistencia';
import { nombrePropio } from '../util/nombres';

const TILE_URL = import.meta.env.VITE_TILES_URL ?? 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
const formatDate = (value: string | null | undefined) => value ? new Date(value).toLocaleString('es-CO', { dateStyle: 'medium', timeStyle: 'short' }) : 'Sin fecha';
const formatShort = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString('es-CO') : 'Nunca';
function FitCoverage({ data }: { data: GeoJSON.FeatureCollection }) { const map = useMap(); useEffect(() => { const layer = new L.GeoJSON(data as never); const bounds = layer.getBounds(); if (bounds.isValid()) map.fitBounds(bounds, { padding: [20, 20], maxZoom: 12 }); }, [data, map]); return null; }
function coverageStyle(feature?: GeoJSON.Feature) { const visits = Number((feature?.properties as { visitas?: number } | undefined)?.visitas ?? 0); return { color: '#ffffff', weight: 1, fillOpacity: .82, fillColor: visits ? (visits > 3 ? '#1c5cab' : '#6da7ec') : '#f6e3b4' }; }

export function AgendaPage() {
  const { tienePermiso } = useSesion(); const gestionar = tienePermiso('AGENDA_GESTIONAR'); const [tab, setTab] = useState('cobertura'); const [visitaId, setVisitaId] = useState<string>(); const [estado, setEstado] = useState(''); const [formError, setFormError] = useState(''); const cache = useQueryClient();
  const cobertura = useQuery({ queryKey: ['agenda', 'cobertura'], queryFn: () => api.agendaCobertura() }); const visitas = useQuery({ queryKey: ['agenda', 'visitas', estado], queryFn: () => api.agendaVisitas(estado ? `estado=${estado}` : '') }); const compromisos = useQuery({ queryKey: ['agenda', 'compromisos'], queryFn: () => api.agendaCompromisos() }); const detalle = useQuery({ queryKey: ['agenda', 'detalle', visitaId], queryFn: () => api.agendaDetalle(visitaId!), enabled: Boolean(visitaId) }); const catalogos = useQuery({ queryKey: ['agenda', 'catalogos'], queryFn: api.agendaCatalogos, enabled: gestionar });
  function abrir(id: string) { setVisitaId(id); setTab('detalle'); }
  return <main className="page-content agenda-page"><div className="page-heading"><div><p className="eyebrow">Presencia y escucha</p><h1>Agenda territorial</h1><p className="dashboard-subtitle">Visitas, necesidades y compromisos del territorio.</p></div>{gestionar && <button className="primary-button" type="button" onClick={() => setTab('nueva')}>Nueva visita</button>}</div><nav className="agenda-tabs" aria-label="Secciones de agenda">{[['cobertura', 'Mapa de cobertura'], ['visitas', 'Visitas'], ['compromisos', 'Compromisos'], ['comparativo', 'Asistencia vs. referidos']].map(([key, label]) => <button key={key} type="button" className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</nav>{tab === 'cobertura' && <CoberturaTab query={cobertura} eventos={visitas.data?.datos ?? []} abrir={abrir} />}{tab === 'comparativo' && <ComparativoAsistencia />}{tab === 'visitas' && <VisitasTab query={visitas} estado={estado} setEstado={setEstado} abrir={abrir} />}{tab === 'detalle' && visitaId && <DetalleTab query={detalle} catalogos={catalogos.data} gestionar={gestionar} onBack={() => setTab('visitas')} onRefresh={() => void cache.invalidateQueries({ queryKey: ['agenda'] })} />}{tab === 'compromisos' && <CompromisosTab query={compromisos} gestionar={gestionar} catalogos={catalogos.data} onRefresh={() => void cache.invalidateQueries({ queryKey: ['agenda', 'compromisos'] })} />}{tab === 'nueva' && <NuevaVisitaForm catalogos={catalogos.data} onCancel={() => setTab('visitas')} onDone={() => { setTab('visitas'); void cache.invalidateQueries({ queryKey: ['agenda', 'visitas'] }); }} />}{formError && <div className="form-error">{formError}</div>}</main>;
}

function CoberturaTab({ query, eventos, abrir }: { query: UseQueryResult<GeoJSON.FeatureCollection>; eventos: AgendaVisita[]; abrir: (id: string) => void }) { const data = query.data; const zonas = data?.features ?? []; const sinMunicipios = zonas.filter(z => z.properties?.tipo === 'MUNICIPIO' && !Number(z.properties?.visitas)); const sinVeredas = zonas.filter(z => ['VEREDA', 'BARRIO'].includes(String(z.properties?.tipo)) && !Number(z.properties?.visitas)); return <section className="agenda-card coverage-layout">{query.isPending && <Cargando texto="Cargando cobertura..." />}{query.isError && <ErrorEstado mensaje={query.error.message} />}{data && <><div className="coverage-map"><MapContainer center={[1.614, -75.606]} zoom={8} className="territory-map"><TileLayer attribution='&copy; OpenStreetMap contributors' url={TILE_URL} /><FitCoverage data={data} /><GeoJSON data={data as never} style={coverageStyle as never} onEachFeature={(feature, layer) => layer.bindPopup(`<strong>${feature.properties?.nombre ?? 'Zona'}</strong><br />Visitas: ${feature.properties?.visitas ?? 0}<br />Última visita: ${formatShort(feature.properties?.ultima_visita)}`)} />{eventos.filter(e => e.lat != null && e.lon != null).map(e => <CircleMarker key={e.id} center={[Number(e.lat), Number(e.lon)]} radius={7} pathOptions={{ color: '#ffffff', weight: 2, fillColor: e.estado === 'PROGRAMADA' ? '#fab219' : '#0b1b2e', fillOpacity: 1 }}><Popup><strong>{e.nombre}</strong><br />{formatDate(e.inicia_en)} · {e.estado}<br /><button type="button" className="link-button" onClick={() => abrir(e.id)}>Ver evento</button></Popup></CircleMarker>)}</MapContainer></div><aside className="coverage-alerts"><h2>Sin visita</h2><h3>Municipios sin visitar <b>{sinMunicipios.length}</b></h3>{sinMunicipios.slice(0, 8).map(z => <span key={String(z.id)}>{nombrePropio(z.properties?.nombre)}</span>)}<h3>Veredas y barrios sin visitar <b>{sinVeredas.length}</b></h3>{sinVeredas.slice(0, 8).map(z => <span key={String(z.id)}>{nombrePropio(z.properties?.nombre)}</span>)}</aside></>}</section>; }

function VisitasTab({ query, estado, setEstado, abrir }: { query: ReturnType<typeof useQuery<{ datos: AgendaVisita[] }>>; estado: string; setEstado: (x: string) => void; abrir: (id: string) => void }) { return <section className="agenda-card"><div className="filter-row"><label>Estado<select value={estado} onChange={e => setEstado(e.target.value)}><option value="">Todos</option><option value="PROGRAMADA">Programada</option><option value="REALIZADA">Realizada</option><option value="CANCELADA">Cancelada</option></select></label></div>{query.isPending && <Cargando />}{query.isError && <ErrorEstado mensaje={query.error.message} />}{query.data?.datos.length === 0 && <div className="empty-inline">No hay visitas para estos filtros.</div>}<div className="agenda-list">{query.data?.datos.map(item => <button className="visit-card" key={item.id} type="button" onClick={() => abrir(item.id)}><div><span className="eyebrow">{item.tipo ?? item.tipo_codigo}</span><h2>{item.nombre}</h2><p>{item.ruta ?? item.territorio} · {formatDate(item.inicia_en)}</p></div><div className="visit-meta"><b className={`state-${item.estado?.toLowerCase()}`}>{item.estado}</b><span>{item.asistentes_aprox ?? 0} asistentes</span><small>{item.planteamientos ?? 0} planteamientos · {item.compromisos ?? 0} compromisos</small></div></button>)}</div></section>; }

function DetalleTab({ query, catalogos, gestionar, onBack, onRefresh }: { query: ReturnType<typeof useQuery<AgendaDetalle>>; catalogos?: AgendaCatalogos; gestionar: boolean; onBack: () => void; onRefresh: () => void }) { const [descripcion, setDescripcion] = useState(''); const [categoria, setCategoria] = useState(''); const [prioridad, setPrioridad] = useState('MEDIA'); if (query.isPending) return <Cargando />; if (query.isError) return <ErrorEstado mensaje={query.error.message} />; if (!query.data) return null; const d = query.data; async function plantear(e: FormEvent) { e.preventDefault(); await api.agendaPlanteamiento(d.visita.id, { descripcion, categoria, prioridad }); setDescripcion(''); onRefresh(); } return <section className="agenda-card detail-card"><button className="back-link" type="button" onClick={onBack}>← Volver a visitas</button><p className="eyebrow">{d.visita.tipo}</p><h1>{d.visita.nombre}</h1><p className="detail-lead">{d.visita.ruta} · {formatDate(d.visita.inicia_en)} · {d.visita.estado}</p><AsistenciaEvento visita={d.visita} gestionar={gestionar} /><div className="detail-grid"><div><h2>Líderes presentes</h2>{d.lideres.map(x => <p key={x.nombre}><strong>{x.nombre}</strong> · {x.cargo}</p>)}<h2>Organizaciones</h2>{d.organizaciones.map(x => <p key={`${x.nombre}-${x.tipo}`}>{x.nombre} · {x.tipo}</p>)}</div><div><h2>Planteamientos</h2>{d.planteamientos.map(x => <article className="mini-item" key={x.id}><strong>{x.categoria_codigo}</strong><span>{x.descripcion}</span><small>{x.prioridad}</small></article>)}{gestionar && <form className="inline-form" onSubmit={plantear}><textarea value={descripcion} onChange={e => setDescripcion(e.target.value)} minLength={10} placeholder="Nuevo planteamiento" required /><select value={categoria} onChange={e => setCategoria(e.target.value)} required><option value="">Categoría</option>{catalogos?.categorias.map(x => <option key={x.codigo} value={x.codigo}>{x.nombre}</option>)}</select><select value={prioridad} onChange={e => setPrioridad(e.target.value)}><option>BAJA</option><option>MEDIA</option><option>ALTA</option></select><button className="primary-button">Agregar planteamiento</button></form>}<h2>Compromisos</h2>{d.compromisos.map(x => <article className="mini-item" key={x.id}><strong>{x.estado}</strong><span>{x.descripcion}</span></article>)}</div></div></section>; }

function CompromisosTab({ query, gestionar, catalogos, onRefresh }: { query: ReturnType<typeof useQuery<AgendaCompromiso[]>>; gestionar: boolean; catalogos?: AgendaCatalogos; onRefresh: () => void }) { const [estado, setEstado] = useState(''); const datos = (query.data ?? []).filter(x => !estado || x.estado === estado); return <section className="agenda-card"><div className="filter-row"><label>Estado<select value={estado} onChange={e => setEstado(e.target.value)}><option value="">Todos</option><option>PENDIENTE</option><option>EN_PROGRAMA</option><option>CUMPLIDO</option><option>DESCARTADO</option></select></label></div>{query.isPending && <Cargando />}{query.isError && <ErrorEstado mensaje={query.error.message} />}{datos.map(item => <article className={`commitment-row ${item.estado === 'PENDIENTE' && Number(item.dias_abierto) > 30 ? 'overdue' : ''}`} key={item.id}><div><strong>{item.descripcion}</strong><span>{item.ruta ?? 'Sin territorio'} · {item.visita ?? 'Sin visita'}</span></div><span>{item.estado} · {item.propuesta ?? 'Sin propuesta'} · {item.dias_abierto ?? 0} días</span>{gestionar && <select value={item.estado ?? ''} onChange={async e => { const next = e.target.value; await api.agendaActualizarCompromiso(item.id, { estado: next }); onRefresh(); }}><option>PENDIENTE</option><option>EN_PROGRAMA</option><option>CUMPLIDO</option><option>DESCARTADO</option></select>}</article>)}</section>; }

function NuevaVisita({ catalogos, onCancel, onDone }: { catalogos?: AgendaCatalogos; onCancel: () => void; onDone: () => void }) { const [form, setForm] = useState({ tipo: 'VISITA_VEREDAL', nombre: '', territorioId: '', iniciaEn: '', terminaEn: '', estado: 'PROGRAMADA', conCandidato: true, asistentesAprox: '', resumen: '' }); const [error, setError] = useState(''); async function enviar(e: FormEvent) { e.preventDefault(); try { await api.agendaCrearVisita({ ...form, territorioId: Number(form.territorioId), asistentesAprox: form.asistentesAprox ? Number(form.asistentesAprox) : undefined, liderIds: [], organizaciones: [] }); onDone(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible guardar la visita.'); } } return <form className="agenda-card visit-form" onSubmit={enviar}><button type="button" className="back-link" onClick={onCancel}>← Cancelar</button><h1>Nueva visita</h1>{error && <div className="form-error">{error}</div>}<label>Tipo<select value={form.tipo} onChange={e => setForm({ ...form, tipo: e.target.value })}>{catalogos?.eventos.filter(x => ['VISITA_VEREDAL', 'REUNION_LIDERES', 'RECORRIDO', 'FORO', 'REUNION', 'CARAVANA'].includes(x.codigo)).map(x => <option key={x.codigo} value={x.codigo}>{x.nombre}</option>)}</select></label><label>Nombre<input value={form.nombre} onChange={e => setForm({ ...form, nombre: e.target.value })} required /></label><label>Territorio ID<input type="number" value={form.territorioId} onChange={e => setForm({ ...form, territorioId: e.target.value })} required /></label><div className="form-columns"><label>Inicia<input type="datetime-local" value={form.iniciaEn} onChange={e => setForm({ ...form, iniciaEn: new Date(e.target.value).toISOString() })} required /></label><label>Termina<input type="datetime-local" value={form.terminaEn} onChange={e => setForm({ ...form, terminaEn: new Date(e.target.value).toISOString() })} required /></label></div><label>Estado<select value={form.estado} onChange={e => setForm({ ...form, estado: e.target.value })}><option>PROGRAMADA</option><option>REALIZADA</option></select></label><label>Asistentes aproximados<input type="number" min="0" value={form.asistentesAprox} onChange={e => setForm({ ...form, asistentesAprox: e.target.value })} /></label><label>Resumen<textarea value={form.resumen} onChange={e => setForm({ ...form, resumen: e.target.value })} /></label><button className="primary-button">Guardar visita</button></form>; }
