import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api } from '../api/cliente';
import { Cargando, ErrorEstado } from '../componentes/Estados';

const initial = { nombres: '', apellidos: '', documento: '', telefono: '', territorioId: '', puestoId: '', aceptaComunicaciones: false };
export function RegistrarPage() {
  const municipios = useQuery({ queryKey: ['municipios'], queryFn: api.municipios }); const politica = useQuery({ queryKey: ['registro-politica'], queryFn: api.politicaRegistro }); const [form, setForm] = useState(initial); const [resultado, setResultado] = useState(''); const [error, setError] = useState(''); const [guardando, setGuardando] = useState(false); const puestos = useQuery({ queryKey: ['registrar-puestos', form.territorioId], queryFn: () => api.puestos(Number(form.territorioId)), enabled: Boolean(form.territorioId) });
  async function enviar(e: FormEvent) { e.preventDefault(); if (!politica.data) return; setError(''); setResultado(''); setGuardando(true); try { const result = await api.registroInterno({ nombres: form.nombres, apellidos: form.apellidos, documento: form.documento, telefono: form.telefono || undefined, territorioId: Number(form.territorioId), puestoId: form.puestoId ? Number(form.puestoId) : undefined, finalidades: ['ORGANIZACION_CAMPANA', ...(form.aceptaComunicaciones ? ['COMUNICACIONES'] : [])], politicaVersion: politica.data.version, aceptaPolitica: true, canal: 'FORMULARIO_WEB' }); setResultado(result.resultado === 'DUPLICADO' ? 'DUPLICADO' : 'REGISTRADO'); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible registrar a la persona.'); } finally { setGuardando(false); } }
  if (municipios.isError) return <main className="page-content"><ErrorEstado mensaje={municipios.error.message} /></main>;
  return <main className="page-content registrar-page"><div className="page-heading"><div><p className="eyebrow">Captura asistida</p><h1>Registrar simpatizante</h1><p className="dashboard-subtitle">Usa este formulario cuando la persona no pueda registrarse desde su celular.</p></div></div>{municipios.isPending && <Cargando />}{resultado && <div className={`registration-result ${resultado === 'DUPLICADO' ? 'duplicate' : ''}`} role="status"><strong>{resultado}</strong><span>{resultado === 'DUPLICADO' ? 'Esta persona ya estaba registrada en la campaña.' : 'Registro realizado correctamente.'}</span><button type="button" className="primary-button" onClick={() => { setForm(initial); setResultado(''); }}>Registrar otra persona</button></div>}{!resultado && <form className="dashboard-block registrar-form" onSubmit={enviar}><h2>Datos de la persona</h2><div className="form-columns"><label>Nombres<input value={form.nombres} onChange={e => setForm({ ...form, nombres: e.target.value })} minLength={2} required /></label><label>Apellidos<input value={form.apellidos} onChange={e => setForm({ ...form, apellidos: e.target.value })} minLength={2} required /></label></div><label>Cédula<input inputMode="numeric" pattern="[0-9]{5,10}" value={form.documento} onChange={e => setForm({ ...form, documento: e.target.value.replace(/\D/g, '') })} required /></label><label>Celular <span className="optional">opcional</span><input inputMode="tel" pattern="3[0-9]{9}" value={form.telefono} onChange={e => setForm({ ...form, telefono: e.target.value.replace(/\D/g, '') })} /></label><label>Municipio<select value={form.territorioId} onChange={e => setForm({ ...form, territorioId: e.target.value })} required><option value="">Selecciona uno</option>{municipios.data?.map(m => <option key={m.id} value={m.id}>{m.nombre}</option>)}</select></label><label>Puesto de votación<select value={form.puestoId} onChange={e => setForm({ ...form, puestoId: e.target.value })}><option value="">No sé / lo consulto después</option>{puestos.data?.map(p => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><details className="policy-step"><summary>Política de tratamiento de datos</summary><p>{politica.data?.texto}</p></details><label className="checkbox-label"><input type="checkbox" required /> La persona autorizó verbalmente el tratamiento de sus datos</label><label className="checkbox-label"><input type="checkbox" checked={form.aceptaComunicaciones} onChange={e => setForm({ ...form, aceptaComunicaciones: e.target.checked })} /> Acepta recibir información de la campaña</label>{error && <div className="form-error" role="alert">{error}</div>}<button className="primary-button" disabled={guardando}>{guardando ? 'Registrando...' : 'Registrar persona'}</button></form>}</main>;
}
