import { useState, type FormEvent } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../api/cliente';
import { Cargando, ErrorEstado } from '../componentes/Estados';

export function ReportarPage() {
  const municipios = useQuery({ queryKey: ['municipios'], queryFn: api.municipios });
  const reportes = useQuery({ queryKey: ['mis-reportes'], queryFn: api.misReportes });
  const cache = useQueryClient();
  const [form, setForm] = useState({ territorioId: '', categoria: '', prioridad: 'MEDIA', descripcion: '' });
  const [mensaje, setMensaje] = useState(''); const [error, setError] = useState(''); const [guardando, setGuardando] = useState(false);
  async function enviar(event: FormEvent) { event.preventDefault(); setError(''); setMensaje(''); setGuardando(true); try { await api.reportarNecesidad({ territorioId: Number(form.territorioId), categoria: form.categoria, prioridad: form.prioridad, descripcion: form.descripcion }); setMensaje('Reporte enviado correctamente.'); setForm({ ...form, descripcion: '' }); await cache.invalidateQueries({ queryKey: ['mis-reportes'] }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'No fue posible enviar el reporte.'); } finally { setGuardando(false); } }
  return <main className="page-content report-page"><div className="page-heading"><div><p className="eyebrow">Voz del territorio</p><h1>Reportar necesidad</h1><p className="dashboard-subtitle">Comparte una necesidad concreta de tu zona para que pueda ser atendida.</p></div></div><section className="report-grid"><form className="dashboard-block report-form" onSubmit={enviar}><h2>Nuevo reporte</h2><label>Municipio<select value={form.territorioId} onChange={e => setForm({ ...form, territorioId: e.target.value })} required><option value="">Selecciona un municipio</option>{municipios.data?.map(m => <option key={m.id} value={m.id}>{m.nombre}</option>)}</select></label><label>Categoría<input value={form.categoria} onChange={e => setForm({ ...form, categoria: e.target.value })} placeholder="Ej. Vías, agua, salud" required /></label><label>Prioridad<select value={form.prioridad} onChange={e => setForm({ ...form, prioridad: e.target.value })}><option value="BAJA">Baja</option><option value="MEDIA">Media</option><option value="ALTA">Alta</option></select></label><label>Descripción<textarea value={form.descripcion} onChange={e => setForm({ ...form, descripcion: e.target.value })} minLength={10} maxLength={1000} rows={6} required /></label>{error && <div className="form-error" role="alert">{error}</div>}{mensaje && <div className="form-success" role="status">{mensaje}</div>}<button className="primary-button" disabled={guardando}>{guardando ? 'Enviando...' : 'Enviar reporte'}</button></form><section className="dashboard-block"><div className="block-heading"><h2>Mis reportes</h2></div>{reportes.isPending && <Cargando texto="Cargando reportes..." />}{reportes.isError && <ErrorEstado mensaje={reportes.error.message} />}{reportes.data?.length === 0 && <div className="empty-inline">Todavía no has enviado reportes.</div>}{reportes.data?.map(reporte => <article className="report-item" key={reporte.id}><div><strong>{reporte.categoria_codigo}</strong><span>{reporte.descripcion}</span></div><small>{reporte.prioridad} · {new Date(reporte.reportada_en).toLocaleDateString('es-CO')}</small></article>)}</section></section></main>;
}
