import { CATEGORIAS as CATEGORIAS_NECESIDAD } from '../../necesidades/categorias.js';
import { Type } from 'class-transformer';
import { ArrayUnique, IsArray, IsBoolean, IsDateString, IsIn, IsInt, IsOptional, IsString, IsUUID, Length, Max, Min } from 'class-validator';

const TIPOS = ['VISITA_VEREDAL', 'REUNION_LIDERES', 'RECORRIDO', 'FORO', 'REUNION', 'CARAVANA'];
const ESTADOS = ['PROGRAMADA', 'REALIZADA', 'CANCELADA'];
const PRIORIDADES = ['ALTA', 'MEDIA', 'BAJA'];

export class VisitasQueryDto { @IsOptional() @Type(() => Number) @IsInt() @Min(1) municipioId?: number; @IsOptional() @IsIn(ESTADOS) estado?: string; @IsOptional() @IsDateString() desde?: string; @IsOptional() @IsDateString() hasta?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) pagina = 1; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) porPagina = 20; }
export class OrganizacionDto { @IsString() @Length(2, 160) nombre!: string; @IsString() @Length(2, 40) tipo!: string; }
export class VisitaDto { @IsIn(TIPOS) tipo!: string; @IsString() @Length(2, 180) nombre!: string; @Type(() => Number) @IsInt() @Min(1) territorioId!: number; @IsDateString() iniciaEn!: string; @IsDateString() terminaEn!: string; @IsIn(['PROGRAMADA', 'REALIZADA']) estado!: string; @IsOptional() @IsBoolean() conCandidato = true; @IsOptional() @Type(() => Number) @IsInt() @Min(0) asistentesAprox?: number; @IsOptional() @IsString() @Length(1, 2000) resumen?: string; @IsOptional() @Type(() => Number) lon?: number; @IsOptional() @Type(() => Number) lat?: number; @IsArray() @ArrayUnique() @IsUUID('4', { each: true }) liderIds: string[] = []; @IsArray() organizaciones: OrganizacionDto[] = []; }
export class ActualizarVisitaDto { @IsOptional() @IsIn(ESTADOS) estado?: string; @IsOptional() @IsString() @Length(1, 2000) resumen?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(0) asistentesAprox?: number; @IsOptional() @IsDateString() iniciaEn?: string; @IsOptional() @IsDateString() terminaEn?: string; @IsOptional() @IsArray() @ArrayUnique() @IsUUID('4', { each: true }) liderIds?: string[]; @IsOptional() @IsArray() organizaciones?: OrganizacionDto[]; }
export class PlanteamientoDto { @IsString() @Length(10, 1000) descripcion!: string; @IsString() categoria!: string; @IsIn(PRIORIDADES) prioridad!: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) territorioId?: number; }
export class ReporteDto { @Type(() => Number) @IsInt() @Min(1) territorioId!: number; @IsString() @Length(10, 1000) descripcion!: string; @IsOptional() @IsIn(CATEGORIAS_NECESIDAD, { message: 'Categoría no válida' }) categoria?: string; @IsIn(PRIORIDADES) prioridad!: string; }
export class CompromisoDto { @IsString() @Length(10, 1000) descripcion!: string; @Type(() => Number) @IsInt() @Min(1) territorioId!: number; @IsOptional() @IsString() categoria?: string; @IsOptional() @IsUUID() eventoId?: string; @IsOptional() @IsArray() @ArrayUnique() @IsUUID('4', { each: true }) necesidadIds?: string[]; @IsOptional() @IsUUID() responsableMiembroId?: string; }
export class ActualizarCompromisoDto { @IsIn(['PENDIENTE', 'EN_PROGRAMA', 'CUMPLIDO', 'DESCARTADO']) estado!: string; @IsOptional() @IsUUID() propuestaId?: string; }
export class CompromisosQueryDto { @IsOptional() @Type(() => Number) @IsInt() @Min(1) municipioId?: number; @IsOptional() @IsIn(['PENDIENTE', 'EN_PROGRAMA', 'CUMPLIDO', 'DESCARTADO']) estado?: string; }